apps/store/urls.py
from django.urls import path
from apps.store.views import product_detail, category_detail, search, add_to_cart, cart_view, remove_from_cart, change_quantity, add_quantity, clear_cart, checkout, invoice

urlpatterns = [
    path('search/', search, name='search'),
    path('add-to-cart/<str:product_id>/<int:quantity>/', add_to_cart, name='add_to_cart'),
    path('add-quantity/<str:product_id>/', add_quantity, name='add_quantity'),
    path('remove-from-cart/<str:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('change-quantity/<str:product_id>/', change_quantity, name='change_quantity'),
    path('clear_cart/', clear_cart, name='clear_cart'),
    path('store/checkout/', checkout, name='checkout'),
    path('store/invoice/<int:pk>', invoice, name='invoce'),
    path('cart/', cart_view, name='cart_view'),
    path('<slug:slug>/', category_detail, name='category_detail'),
    path('<slug:category_slug>/<slug:slug>/', product_detail, name='product_detail'),
]

crazyvegans_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('apps.account.urls')),
    path('', include('apps.core.urls')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'apps.core.views.error_400'
handler403 = 'apps.core.views.error_403'
handler404 = 'apps.core.views.error_404'
handler505 = 'apps.core.views.error_505'

admin.site.site_header  =  "Administración de Crazy Vegan"  
admin.site.site_title  =  "Pagina de Administración de Crazy Vegan"
admin.site.index_title  =  "Administración de Crazy Vegan"

apps/store/models.py
from django.db import models
from apps.helper.utilities import pkgen
from apps.account.models import Account
from datetime import date

class Category(models.Model):
    id_category = models.CharField(max_length=8, primary_key=True, default=pkgen)
    name_category = models.CharField(max_length=255, null = False, unique=True)
    description_category = models.TextField(null = False)
    image_category = models.ImageField(blank=False, null=False, upload_to='Category')
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        verbose_name= 'Categoria'
        verbose_name_plural = 'Categorias'
    
    def natural_key(self):
        return (self.id_category)
    
    def __str__(self):
        return self.name_category

class Product(models.Model):
    id_product = models.CharField(max_length=8, primary_key=True, default=pkgen)
    name_product = models.CharField(max_length=255, null=False)
    price_product = models.DecimalField(max_digits=12, decimal_places=2, null=False)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    description_product = models.TextField(null = False)
    stock_product = models.IntegerField(null = False)
    image_product = models.ImageField(blank=False, null=False, upload_to='Items/')
    slug = models.SlugField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_offer = models.BooleanField(default=False)
    percent_offer = models.IntegerField(default= 0)
    offer_end_date = models.DateField(blank=True, null=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name= 'Producto'
        verbose_name_plural = 'Productos'
    
    def __str__(self):
        return self.name_product
    
    @property
    def price_total(self):
        result = self.price_product - (self.price_product * self.percent_offer) / 100
        return result
    
    @property
    def calc_offer_date(self):
        today_now = date.today()
        date_offer = self.offer_end_date
        if self.offer_end_date:
            if date_offer >= today_now:
                return True
            else:
                return False


class Order(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    receiver = models.CharField(max_length=255, blank=True, null=True, default="")
    receiver_address = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255)
    shipping_address = models.CharField(max_length=255, null=True, blank=True)
    shipping_name = models.CharField(max_length=255, null=True, blank=True)
    total_cost = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    paid_amount = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    paid_method = models.CharField(max_length=255, null=True)
    paid_account = models.CharField(max_length=255, blank=True, null=True)
    merchant_id = models.CharField(max_length= 500)
    created_by = models.ForeignKey(Account, related_name='orders', on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name= 'Orden'
        verbose_name_plural = 'Ordenes'

    def get_total_price(self):
        if self.paid_amount:
            return self.paid_amount
        return 0
    
    def __str__(self):
        return f'Orden: {self.id}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    quantity = models.IntegerField(default=1)

    class Meta:
        verbose_name= 'Articulo Orden'
        verbose_name_plural = 'Articulos de la Orden'

    def get_total_price(self):
        return self.price
    
    def __str__(self):
        return f'{self.order}'

apps/store/forms.py
from django import forms
from .models import Product, Order, OrderItem

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'address', 'receiver', 'receiver_address', 'paid_method', 'paid_account')

apps/store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from apps.store.models import Product, Category, Order, OrderItem
from apps.store.cart import Cart
from apps.store.forms import OrderForm
from apps.account.models import Account


#Decoradores
from django.contrib.auth.decorators import login_required
#Carrito
def add_to_cart(request, product_id, quantity):
    cart = Cart(request)
    quantity = int(quantity)
    print(cart)
    cart.add(product_id, quantity)  
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

#Agregar cantidad variable en el detalle 
def add_quantity(request, product_id):
    query = int(request.GET.get('query', ''))
    cart = Cart(request)
    quantity = int(query)
    cart.add(product_id, quantity)
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

def remove_from_cart(request, product_id):
    cart = Cart(request)
    cart.remove(str(product_id))
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

def change_quantity(request, product_id):
    action = request.GET.get('action', '')
    if action:
        quantity = 1
        if action == 'decrease':
            quantity = -1
        cart = Cart(request)
        cart.add(product_id, quantity, True)
    
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

def cart_view(request):
    cart = Cart(request)
    return render(request, 'store/cart_view.html', {
        'cart': cart
    })

@login_required
def checkout(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderForm(request.POST)

        if form.is_valid():
            total_price = 0

            for item in cart:
                product = item['product']
                total_price += product.price_product * int(item['quantity'])

            order = form.save(commit=False)
            order.created_by = request.user
            order.paid_amount = total_price
            if order.receiver_address != None:
                order.shipping_address = order.receiver_address
                order.shipping_name = order.receiver
            else:
                order.shipping_address = order.address
                order.shipping_name = f'{order.first_name}  {order.last_name}'
            order.save()

            for item in cart:
                product = item['product']
                quantity = int(item['quantity'])
                price = product.price_product * quantity

                item = OrderItem.objects.create(order=order, product=product, price=price, quantity=quantity)

            cart.clear()

            return redirect('/store/invoice/' + str(order.id))
    else:
        form = OrderForm()

    return render(request, 'store/checkout.html', {
        'cart': cart,
        'form': form,
    })

#fin del carrito
def category_detail(request, slug):
    category = get_object_or_404(Category, slug = slug)
    products = category.products.all().order_by('-created_at').filter(is_offer = False)

    p = Paginator(products, 9)
    
    page_number = request.GET.get('page')
    try:
         page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)

    return render(request, 'store/category_detail.html', {
        'category' : category,
        'page_obj' : page_obj,
    })

def product_detail(request, category_slug, slug):
    product = get_object_or_404(Product, slug = slug)
    return render(request, 'store/product_detail.html', {
        'product' : product
    })

def search(request):
    query = request.GET.get('query', '')

    if query == "":
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    
    products = Product.objects.filter(name_product__icontains=query).filter(is_offer = False)
    
    p = Paginator(products, 9)
    
    page_number = request.GET.get('page')
    try:
         page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)

    return render(request, 'store/search.html', {
        'query':query,
        'page_obj' : page_obj,
    })

#Ventana de Gracias
def invoice(request, pk):
    order = get_object_or_404(Order, pk = pk)
    orderitems = OrderItem.objects.filter(order = pk).distinct()
    if order.receiver_address != None:
        order.shipping_address = order.receiver_address
        order.shipping_name = order.receiver
    else:
        order.shipping_address = order.address
        order.shipping_name = f'{order.first_name}  {order.last_name}'

    return render(request, 'store/invoice.html', {
        'order' : order,
        'orderitems' : orderitems
    })

apps/store/templates/store/cart_view.html
{% extends 'core/base.html' %}
{% load static %}
{% block content%}

  {% for item in cart %}
  <div class="row align-items-center border-bottom" style="height:150x; width:450px">
    <!--Imagen -->
    <div class="col">
      <img src="{{ item.product.image_product.url }}" class="" style="width: 75px;">
    </div>
    <!--Titulo, Precio y Cantidad-->
    <div class="col-6">
      <div class="row">
        <span class ="col-8">
          {{ item.product.name_product}}
        </span>
        <span class ="col">
          Cant:
          <strong>{{ item.quantity }}</strong>
        </span>
        <span class ="col">
          <span class="text-muted">${{ item.product.price_total}}</span>
        </span>
      </div>
    </div>
    <!-- Botones -->
    <div class="col">
      <div class="row" style="margin:3px;">
        <a class ="col-md-6 col-lg-3 col-xl-3  " href="{% url 'change_quantity' item.product.id_product %}?action=increase">
            <img class="account-image rounded-circle m-auto d-block dropdown-toggle" aria-haspopup="true" aria-expanded="false" src="{% static "images/icons/plus.png" %}" alt="Usuarios" width="25" height="25">
        </a>
        <a class ="col-md-6 col-lg-3 col-xl-3 "  href="{% url 'change_quantity' item.product.id_product %}?action=decrease">
            <img class="account-image rounded-circle m-auto d-block dropdown-toggle" aria-haspopup="true" aria-expanded="false" src="{% static "images/icons/minus.png" %}" alt="Usuarios" width="25" height="25">
        </a>
        <a class ="col-md-6 col-lg-3 col-xl-3 " href="{% url 'remove_from_cart' item.product.id_product %}">
            <img class="account-image rounded-circle m-auto d-block dropdown-toggle" aria-haspopup="true" aria-expanded="false" src="{% static "images/icons/trash.png" %}" alt="Usuarios" width="25" height="25">
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
  <div>
  </div>
  <p>Costo total: <strong>{{ cart.get_total_cost  }}</strong></p>
  {% endblock %}

apps/store/templates/store/category_detail.html
{% extends 'core/base.html' %}
{% load drop_menu %}

{%block title%} Categories {%endblock%}
{% block content%}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Categoria</li>
    </ol>
  </nav>
<div class="container-fluid" style="margin-left: 7%;">
    <div class ="row pb-0 justify-content-end" style="margin-left: 74%;">
        {% drop_menu %}
    </div>
    <div class="row p-3 pb-2 pt-3">
        {% for product in page_obj.object_list %}
            <div class="card col-xs-12 col-md-6 col-lg-3" style="width: 18rem; margin: 10px; border-radius: 30px;">
                <div class="container d-flex align-items-center justify-content-center pt-4" style="width: 200px; height: 120px;">
                    <a href="{% url 'product_detail' product.category.slug product.slug %}" style="text-decoration:none; color: #000000; opacity:0.87;"><img src="{{ product.image_product.url }}" class="rounded mx-auto d-block" style="width: 100%; max-width:195px; max-height:115px" ></a>
                </div>
                <div class="card-body">
                    <div style="display: flex; flex-direction: row" class="pt-2">
                        <h5 class="card-title"> <a href="{% url 'product_detail' product.category.slug product.slug %}" style="text-decoration:none; color: #000000; opacity:0.87;">{{ product.name_product }}</a></h5>
                    </div>
                    <div class="pt-1">
                        <strong class="card-text">$ {{ product.price_product}}</strong>
                        <p class="card-text">{{ product.description_product}}</p>
                    </div>                                 
                </div>             
                <div class="card-footer text-end pt-3" style="background-color:white;">
                    <a href="{% url 'add_to_cart' product.id_product 1 %}" class="btn call-to-action text-white"> Agregar al carrito</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<center>
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
          <li class="page-item">
            {%if page_obj.has_previous %} {# si existe la página anterior #}
                <a href="?page={{page_obj.previous_page_number}}" class="page-link"><i class="fa-solid fa-chevron-left pag-link"></i></a></li> {# Link de la pagina anterior #}
            {% endif %}
          </li>
          
          <li class="page-item"><a class="page-link">{{ page_obj.number }}</a></li>
        
          <li class="page-item">
            {%if page_obj.has_next %} {# Revisa si existe otra pagina #}
                <a href="?page={{page_obj.next_page_number}}" class="page-link"><i class="fa-solid fa-chevron-right pag-link"></i></a> {# Link de la siguiente pagina#}
                {% endif %}
            
          </li>
        </ul>
      </nav>
</center>
{% endblock %}

apps/store/templates/store/checkout.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<form method="post" action="."> {% csrf_token %}
  <div class="d-flex justify-content-between align-items-center mb-5">
    <div class="d-flex flex-row align-items-center">
      <h3 class="mt-1 text-2xl">Información de Compra</h3>
    </div>
    <a href="/" class="text-black" style="color: black; opacity: 0.87;"><i class="fa fa-arrow-left"></i>Volver</a>
  </div>

  <div class="row">
    <div class="col-md-7 col-lg-7 col-xl-6 mb-4 mb-md-0">
      <div class="p-2 d-flex align-items-center border-bottom" style="background-color: #eee;">
        <input type="radio" id="id_mercado_pago", name="paid_method", value="Mercado Pago" class="form-check-input m-1">
          <label for="mercado_pago" class="form-check-label"> Mercado Pago <img src="{% static 'images/icons/mercado_pago.png' %}" width="25" height="25"></label>
      </div>
      <div class="p-2 d-flex align-items-center border-top" style="background-color: #eee;">
          <input type="radio" id="transferencia", name="paid_method", value="Transferencia" class="form-check-input m-1">
          <label for="transferencia" class="form-check-label"> Transferencia Bancaria </label> &nbsp <i class="fa-solid fa-money-bill-transfer" style="color: #68a047; font-size:20px"></i>
      </div>
      <div class="p-2 d-flex align-items-center" style="background-color: #eee;">
        <input id="id_paid_account" type="text" name="paid_account" maxlength="255" class="form-control" placeholder="Numero de Cuenta..."  pattern="\d*" minlength="7" title="Solo acepta NUMEROS y un mínimo de 7 dígitos">
    </div>
      <div>
        <div class="d-flex justify-content-between">
          <div class="d-flex flex-row mt-1">
            <h3>Verifique sus datos</h3>
          </div>
          <div class="d-flex flex-row align-items-center text-primary">
          </div>
        </div>
        <div class="p-2 d-flex align-items-center">
        <input id="id_first_name" type="text" name="first_name" maxlength="255" required="" class="form-control" value="{{user.firstname}}" readonly>
        <input id="id_last_name" type="text" name="last_name" maxlength="255" required="" class="form-control" value="{{user.lastname}}" readonly>
        </div>   
        <div class="p-2 d-flex align-items-center">
          <textarea id="id_address" type="text" name="address" maxlength="255" required="" class="form-control" readonly>{{user.direction}}</textarea>
        </div>
        <hr />
        <div class="d-flex justify-content-between align-items-center">
          <div class="d-flex flex-row mt-1">
            <h3>Ticket de regalo</h3>
          </div>
        </div>
        <div class="p-2 d-flex align-items-center">
          <input id="id_receiver" type="text" name="receiver" maxlength="255" class="form-control" placeholder="Nombres y Apellidos">    
        </div>  
        <div class="p-2 d-flex align-items-center">
          <textarea id="id_receiver_address" type="text" name="receiver_address" maxlength="255" class="form-control" placeholder="Dirección"></textarea>
        </div>
        <hr />
        <div class="d-flex justify-content-between align-items-center">
          <div class="d-flex flex-row mt-1">
            <h3>Carrito</h3>
          </div>
        </div>        
          {% for item in cart %}
          <div class="d-flex justify-content-between align-items-center">
            <div class="row">
              <div class="col-2">
            <img src="{{ item.product.image_product.url }}" class="m-2" style="width: 75px;">
              </div>
            <div class="col m-2">
              <span class="m-2 align-items-center">{{ item.product.name_product}}</span>
            </div>
            <div class="col m-2">
            <span class="text-muted m-2 align-items-center">${{ item.product.price_product}}</span> 
            Cant: <strong>{{ item.quantity }}</strong>
            </div>
          </div>
        </div>
        {% endfor %} 
      </div>
        <!--Esto debera ser borrado con cuidado-->         
    </div>
    <!--Columna de la derecha-->
    <div class="col-md-5 col-lg-4 col-xl-4 offset-lg-1 offset-xl-2">
      <div class="p-3" style="background-color: #eee;">
        <span class="fw-bold">Orden</span>
        <div class="d-flex justify-content-between mt-2">
          <span>Sub-Total:</span> <span>${{ cart.get_total_cost}}</span>
        </div>
        <div class="d-flex justify-content-between mt-2">
          <span>Envió gratis:</span> <span>$0.0</span>
        </div>                
        <hr />
        <div class="d-flex justify-content-between mt-2">
          <span class="fw-bold">Total: </span> <span class="text-success">${{ cart.get_total_cost}}</span>
        </div>
      </div>
      <button type="submit" class="btn btn-primary btn-lg call-to-action align-items-center" style="font-size: 20px; width:100%;">Confirmación y Pago</button>
    </div>
  </div>
  {% for field in form %}
        <p>
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
    {% endfor %}
        {% if form.non_field_errors %}
            <div style="color: red">
                <p>{{form.non_field_errors}}</p>
            </div>
        {% endif %}
</form>

<script>
  document.getElementById("transferencia").addEventListener('change', function(){
  document.getElementById("id_paid_account").required = this.checked ;
  })

  document.getElementById("id_mercado_pago").addEventListener('change', function(){
    document.getElementById("id_paid_account").required = false ;
  })
</script>
{% endblock %}

apps/store/templates/store/invoice.html
{% extends 'core/base.html' %}
{% load static %}
{%block title%} Products {%endblock%}
{% block content%}
<div id='printable_div_id'>
  
<div class="container mt-6 mb-7">
    <div class="row justify-content-center">
      <div class="col-lg-12 col-xl-7">
        <div class="card">
          <div class="card-body p-5">
            <img src="{% static "images/company/provisional_logo.png" %}" width="145" height="60">
            <h3 class="pt-3">
              Hey {{order.first_name}}
            </h3>
            <p class="fs-sm">
              Muchas gracias por su compra en <strong>Crazy Vegan</strong>. Esperamos que tenga hoy y siempre el mejor de los días.
            </p>

            <div class="border-top border-gray-200 pt-4 mt-4">
              <div class="row">
                <div class="col-md-6">
                  <div class="text-muted mb-2">Numero de Factura.</div>
                  <strong>{{order.id}} </strong>
                </div>
                <div class="col-md-6 text-md-end">
                  <div class="text-muted mb-2">Fecha de pago</div>
                  <strong>{{order.created_at}}</strong>
                </div>          
              </div>
            </div>

            <div class="border-top border-gray-200 mt-4 py-4">
              <div class="row">
                <div class="col-md-6">
                  <div class="text-muted mb-2">Cliente</div>
                  <strong>
                    {{order.first_name}} {{order.last_name}}
                  </strong>
                  <p class="fs-sm">
                    {{ order.address }}
                    <br>
                    {{order.paid_method}}
                  </p>             
                </div>
                <div class="col-md-6 text-md-end">
                  <div class="text-muted mb-2">Pago a</div>
                  <strong>
                    Crazy Vegan
                  </strong>
                  <p class="fs-sm">
                    Avenida Siempre viva No.5
                    <br>
                    <a href="#!" class="text-purple">crazyvegan@mail.com
                    </a>
                  </p>
                </div>

                <div class="row text-md-start pt-4">
                  <p class="fs-sm">
                    <strong>Destinatario:</strong>
                    <br>
                    <span class="">{{order.shipping_name}}
                    </span>
                  </p>
                  <p class="fs-sm">
                    <strong>Dirección de envió</strong>
                    <br>
                    <span class="">{{order.shipping_address}}
                    </span>
                  </p>
                </div>
              </div>
            </div>

            <table class="table border-bottom border-gray-200 mt-3">
              <thead>
                <tr>
                  <th scope="col" class="fs-sm text-dark text-uppercase-bold-sm px-0">Descripción</th>
                  <th scope="col" class="fs-sm text-dark text-uppercase-bold-sm text-end px-0">Monto</th>
                  <th scope="col" class="fs-sm text-dark text-uppercase-bold-sm text-end px-0">Cant.</th>
                </tr>
              </thead>
              <tbody>                     
                {% for item in orderitems %}
                <tr>
                    <td class="px-0">{{item.product}}</td>
                    <td class="text-end px-0">{{item.price}}</td>
                    <td class="text-end px-0">{{item.quantity}}</td>
                <tr>
                {% endfor %}
              </tbody>
            </table>

            <div class="mt-5">
              <div class="d-flex justify-content-end">
                <p class="text-muted me-3">Subtotal:</p>
                <span>{{order.paid_amount}}</span>
              </div>
              <div class="d-flex justify-content-end">
                <p class="text-muted me-3">Envió</p>
                <span>$0</span>
              </div>
              <div class="d-flex justify-content-end mt-3">
                <h5 class="me-3">Total:</h5>
                <h5 class="text-success">${{order.paid_amount}}</h5>
              </div>
            </div>
          </div>
          <div class="d-print-none non-printable">
            <div class="float-end">
                <a onClick="printdiv('printable_div_id');" class="btn call-to-action me-1"><i class="fa fa-print"></i></a>
            </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
  <script>
    function printdiv(elem) {
      var header_str = '<html><head><title>' + document.title  + '</title></head><body>';
      var footer_str = '</body></html>';
      var new_str = document.getElementById(elem).innerHTML;
      var old_str = document.body.innerHTML;
      document.body.innerHTML = header_str + new_str + footer_str;
      window.print();
      document.body.innerHTML = old_str;
      return false;
    }
    </script>
{% endblock %}

apps/store/templates/store/product_detail.html
{% extends 'core/base.html' %}
{% load static %}
{%block title%} Detalle del Producto {%endblock%}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><a href="/product">Producto</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{product.name_product}}</li>
    </ol>
  </nav>
<div class="container mt-5 mb-5 rounded">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="images p-3">
                            <div class="text-center p-4"> <img src="{{ product.image_product.url }}" width="250" /> </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product p-4">
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="/"class="d-flex align-items-center"><i class="fa-solid fa-arrow-left" style="font-size: 20px; color: black;"></i></a>
                            </div>
                            <div class="mt-4 mb-3"> <span class="text-uppercase text-muted brand">{{ product.name_category }}</span>
                                <h5 class="text-uppercase">{{product.name_product}}</h5>
                                <div class="price d-flex flex-row align-items-center"> <span class="act-price">$ {{ product.price_product }}</span>
                                </div>
                            </div>
                            <p class="about">{{ product.description_product }}</p>
                            <div class="w-50" style="margin:13px;">
                                <h6 class="text-muted row">Cantidad (Maximo10)</h6>
                                <form action ="{% url 'add_quantity' product.id_product %}" class = "row" method="get">                        
                                    <input type="number" placeholder="Cantidad" name="query" id="value" class="form-control" min="1" max="10" value="1">
                                    <button type="submit" class="btn call-to-action btn-main-menu text-white">Agregar al carrito</button>
                                </form>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById("value").addEventListener("change", function() {
        let valor = parseInt(this.value);
        if (valor < 1) this.value = 1;
        if (valor > 50) this.value = 10;
      });
</script>
{%endblock%}